version: '3.8'

services:

  # Base de datos de pagos
  db-pagos:
    image: mysql:8.0
    container_name: db-pagos
    environment:
      MYSQL_DATABASE: db_pagos
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    networks:
      - homerent-net

  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - homerent-net

  # Eureka Server
  ms-eureka:
    build: ./MS-Eureka
    container_name: ms-eureka
    ports:
      - "8761:8761"
    networks:
      - homerent-net

  # MS-Pagos
  ms-pagos:
    build: ./MS-Pagos
    container_name: ms-pagos
    ports:
      - "8085:8085"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db-pagos:3306/db_pagos
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_RABBITMQ_HOST: rabbitmq
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://ms-eureka:8761/eureka/
    depends_on:
      - db-pagos
      - rabbitmq
      - ms-eureka
    networks:
      - homerent-net

   Gateway
  ms-gateway:
    build: ./MS-Gateway
    container_name: ms-gateway
    ports:
      - "8080:8080"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://ms-eureka:8761/eureka/
    depends_on:
      - ms-eureka
  networks:
      - homerent-net

networks:
  homerent-net:
    driver: bridge